### ISSUE TITLE
yiimp Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by crombiecrunch** [216k155/Yiimp-PHI1612-Implemented#1]
the stratum builds fine and will load, but as soon as you connect the coin to the phi1612 algo you get 
Segmentation fault      (core dumped)
ERROR: apport (pid 11875) Fri Oct  6 12:05:16 2017: is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
`ProblemType: Crash
Architecture: amd64
CrashCounter: 1
Date: Fri Oct  6 11:54:59 2017
DistroRelease: Ubuntu 16.04
ExecutablePath: /var/stratum/stratum
ExecutableTimestamp: 1507305267
ProcCmdline: ./stratum /var/stratum/config/phi1612
ProcCwd: /var/stratum
ProcEnviron:
 SHELL=/bin/bash
 TERM=xterm
 PATH=(custom, user)
 LANG=en_US.UTF-8
 XDG_RUNTIME_DIR=<set>
ProcMaps:
 00400000-00647000 r-xp 00000000 08:01 768003                             /var/stratum/stratum
 00846000-00847000 r--p 00246000 08:01 768003                             /var/stratum/stratum
 00847000-00857000 rw-p 00247000 08:01 768003                             /var/stratum/stratum
 00857000-00859000 rw-p 00000000 00:00 0 
 01e33000-01ec3000 rw-p 00000000 00:00 0                                  [heap]
 7f73e9545000-7f73e9546000 ---p 00000000 00:00 0 
 7f73e9546000-7f73e9d46000 rw-p 00000000 00:00 0 
 7f73e9d46000-7f73e9d47000 ---p 00000000 00:00 0 
 7f73e9d47000-7f73ea547000 rw-p 00000000 00:00 0 
 7f73ea547000-7f73ea548000 ---p 00000000 00:00 0 
 7f73ea548000-7f73ead48000 rw-p 00000000 00:00 0 
 7f73ead48000-7f73ead53000 r-xp 00000000 08:01 2044                       /lib/x86_64-linux-gnu/libnss_files-2.23.so
 7f73ead53000-7f73eaf52000 ---p 0000b000 08:01 2044                       /lib/x86_64-linux-gnu/libnss_files-2.23.so
 7f73eaf52000-7f73eaf53000 r--p 0000a000 08:01 2044                       /lib/x86_64-linux-gnu/libnss_files-2.23.so
 7f73eaf53000-7f73eaf54000 rw-p 0000b000 08:01 2044                       /lib/x86_64-linux-gnu/libnss_files-2.23.so
 7f73eaf54000-7f73eaf5a000 rw-p 00000000 00:00 0 
 7f73eaf5a000-7f73eaf63000 r-xp 00000000 08:01 2045                       /lib/x86_64-linux-gnu/libcrypt-2.23.so
 7f73eaf63000-7f73eb162000 ---p 00009000 08:01 2045                       /lib/x86_64-linux-gnu/libcrypt-2.23.so
 7f73eb162000-7f73eb163000 r--p 00008000 08:01 2045                       /lib/x86_64-linux-gnu/libcrypt-2.23.so
 7f73eb163000-7f73eb164000 rw-p 00009000 08:01 2045                       /lib/x86_64-linux-gnu/libcrypt-2.23.so
 7f73eb164000-7f73eb192000 rw-p 00000000 00:00 0 
 7f73eb192000-7f73eb261000 r-xp 00000000 08:01 25914                      /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
 7f73eb261000-7f73eb461000 ---p 000cf000 08:01 25914                      /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
 7f73eb461000-7f73eb464000 r--p 000cf000 08:01 25914                      /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
 7f73eb464000-7f73eb466000 rw-p 000d2000 08:01 25914                      /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
 7f73eb466000-7f73eb467000 rw-p 00000000 00:00 0 
 7f73eb467000-7f73eb4ae000 r-xp 00000000 08:01 25990                      /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
 7f73eb4ae000-7f73eb6ad000 ---p 00047000 08:01 25990                      /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
 7f73eb6ad000-7f73eb6af000 r--p 00046000 08:01 25990                      /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
 7f73eb6af000-7f73eb6b1000 rw-p 00048000 08:01 25990                      /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
 7f73eb6b1000-7f73eb6b2000 rw-p 00000000 00:00 0 
 7f73eb6b2000-7f73eb6c0000 r-xp 00000000 08:01 25983                      /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
 7f73eb6c0000-7f73eb8bf000 ---p 0000e000 08:01 25983                      /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
 7f73eb8bf000-7f73eb8c0000 r--p 0000d000 08:01 25983                      /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
 7f73eb8c0000-7f73eb8c1000 rw-p 0000e000 08:01 25983                      /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
 7f73eb8c1000-7f73eb8e8000 r-xp 00000000 08:01 25987                      /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
 7f73eb8e8000-7f73ebae8000 ---p 00027000 08:01 25987                      /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
 7f73ebae8000-7f73ebae9000 r--p 00027000 08:01 25987                      /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
 7f73ebae9000-7f73ebaea000 rw-p 00028000 08:01 25987                      /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
 7f73ebaea000-7f73ebaff000 r-xp 00000000 08:01 25977                      /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
 7f73ebaff000-7f73ebcfe000 ---p 00015000 08:01 25977                      /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
 7f73ebcfe000-7f73ebcff000 r--p 00014000 08:01 25977                      /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
 7f73ebcff000-7f73ebd00000 rw-p 00015000 08:01 25977                      /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
 7f73ebd00000-7f73ebd30000 r-xp 00000000 08:01 25981                      /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
 7f73ebd30000-7f73ebf30000 ---p 00030000 08:01 25981                      /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
 7f73ebf30000-7f73ebf31000 r--p 00030000 08:01 25981                      /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
 7f73ebf31000-7f73ebf32000 rw-p 00031000 08:01 25981                      /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
 7f73ebf32000-7f73ebf33000 rw-p 00000000 00:00 0 
 7f73ebf33000-7f73ebfd2000 r-xp 00000000 08:01 25979                      /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
 7f73ebfd2000-7f73ec1d1000 ---p 0009f000 08:01 25979                      /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
 7f73ec1d1000-7f73ec1d2000 r--p 0009e000 08:01 25979                      /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
 7f73ec1d2000-7f73ec1d5000 rw-p 0009f000 08:01 25979                      /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
 7f73ec1d5000-7f73ec259000 r-xp 00000000 08:01 25992                      /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
 7f73ec259000-7f73ec458000 ---p 00084000 08:01 25992                      /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
 7f73ec458000-7f73ec45b000 r--p 00083000 08:01 25992                      /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
 7f73ec45b000-7f73ec45e000 rw-p 00086000 08:01 25992                      /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
 7f73ec45e000-7f73ec45f000 rw-p 00000000 00:00 0 
 7f73ec45f000-7f73ec467000 r-xp 00000000 08:01 25994                      /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
 7f73ec467000-7f73ec666000 ---p 00008000 08:01 25994                      /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
 7f73ec666000-7f73ec667000 r--p 00007000 08:01 25994                      /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
 7f73ec667000-7f73ec668000 rw-p 00008000 08:01 25994                      /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
 7f73ec668000-7f73ec66b000 r-xp 00000000 08:01 2247                       /lib/x86_64-linux-gnu/libkeyutils.so.1.5
 7f73ec66b000-7f73ec86a000 ---p 00003000 08:01 2247                       /lib/x86_64-linux-gnu/libkeyutils.so.1.5
 7f73ec86a000-7f73ec86b000 r--p 00002000 08:01 2247                       /lib/x86_64-linux-gnu/libkeyutils.so.1.5
 7f73ec86b000-7f73ec86c000 rw-p 00003000 08:01 2247                       /lib/x86_64-linux-gnu/libkeyutils.so.1.5
 7f73ec86c000-7f73ec873000 r-xp 00000000 08:01 25873                      /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
 7f73ec873000-7f73eca72000 ---p 00007000 08:01 25873                      /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
 7f73eca72000-7f73eca73000 r--p 00006000 08:01 25873                      /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
 7f73eca73000-7f73eca74000 rw-p 00007000 08:01 25873                      /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
 7f73eca74000-7f73ecab1000 r-xp 00000000 08:01 25997                      /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
 7f73ecab1000-7f73eccb1000 ---p 0003d000 08:01 25997                      /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
 7f73eccb1000-7f73eccb2000 r--p 0003d000 08:01 25997                      /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
 7f73eccb2000-7f73eccb4000 rw-p 0003e000 08:01 25997                      /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
 7f73eccb4000-7f73eccb5000 rw-p 00000000 00:00 0 
 7f73eccb5000-7f73eccce000 r-xp 00000000 08:01 26020                      /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
 7f73eccce000-7f73ecece000 ---p 00019000 08:01 26020                      /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
 7f73ecece000-7f73ececf000 r--p 00019000 08:01 26020                      /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
 7f73ececf000-7f73eced0000 rw-p 0001a000 08:01 26020                      /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
 7f73eced0000-7f73ecee7000 r-xp 00000000 08:01 2059                       /lib/x86_64-linux-gnu/libresolv-2.23.so
 7f73ecee7000-7f73ed0e7000 ---p 00017000 08:01 2059                       /lib/x86_64-linux-gnu/libresolv-2.23.so
 7f73ed0e7000-7f73ed0e8000 r--p 00017000 08:01 2059                       /lib/x86_64-linux-gnu/libresolv-2.23.so
 7f73ed0e8000-7f73ed0e9000 rw-p 00018000 08:01 2059                       /lib/x86_64-linux-gnu/libresolv-2.23.so
 7f73ed0e9000-7f73ed0eb000 rw-p 00000000 00:00 0 
 7f73ed0eb000-7f73ed0f5000 r-xp 00000000 08:01 25961                      /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
 7f73ed0f5000-7f73ed2f4000 ---p 0000a000 08:01 25961                      /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
 7f73ed2f4000-7f73ed2f5000 r--p 00009000 08:01 25961                      /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
 7f73ed2f5000-7f73ed2f6000 rw-p 0000a000 08:01 25961                      /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
 7f73ed2f6000-7f73ed2f9000 r-xp 00000000 08:01 2034                       /lib/x86_64-linux-gnu/libcom_err.so.2.1
 7f73ed2f9000-7f73ed4f8000 ---p 00003000 08:01 2034                       /lib/x86_64-linux-gnu/libcom_err.so.2.1
 7f73ed4f8000-7f73ed4f9000 r--p 00002000 08:01 2034                       /lib/x86_64-linux-gnu/libcom_err.so.2.1
 7f73ed4f9000-7f73ed4fa000 rw-p 00003000 08:01 2034                       /lib/x86_64-linux-gnu/libcom_err.so.2.1
 7f73ed4fa000-7f73ed526000 r-xp 00000000 08:01 25964                      /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
 7f73ed526000-7f73ed725000 ---p 0002c000 08:01 25964                      /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
 7f73ed725000-7f73ed727000 r--p 0002b000 08:01 25964                      /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
 7f73ed727000-7f73ed728000 rw-p 0002d000 08:01 25964                      /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
 7f73ed728000-7f73ed729000 rw-p 00000000 00:00 0 
 7f73ed729000-7f73ed7ec000 r-xp 00000000 08:01 25971                      /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
 7f73ed7ec000-7f73ed9ec000 ---p 000c3000 08:01 25971                      /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
 7f73ed9ec000-7f73ed9f9000 r--p 000c3000 08:01 25971                      /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
 7f73ed9f9000-7f73ed9fb000 rw-p 000d0000 08:01 25971                      /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
 7f73ed9fb000-7f73eda0c000 r-xp 00000000 08:01 25833                      /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
 7f73eda0c000-7f73edc0c000 ---p 00011000 08:01 25833                      /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
 7f73edc0c000-7f73edc0d000 r--p 00011000 08:01 25833                      /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
 7f73edc0d000-7f73edc0e000 rw-p 00012000 08:01 25833                      /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
 7f73edc0e000-7f73edc67000 r-xp 00000000 08:01 25831                      /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
 7f73edc67000-7f73ede66000 ---p 00059000 08:01 25831                      /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
 7f73ede66000-7f73ede70000 r--p 00058000 08:01 25831                      /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
 7f73ede70000-7f73ede72000 rw-p 00062000 08:01 25831                      /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
 7f73ede72000-7f73edea4000 r-xp 00000000 08:01 25825                      /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
 7f73edea4000-7f73ee0a3000 ---p 00032000 08:01 25825                      /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
 7f73ee0a3000-7f73ee0a4000 r--p 00031000 08:01 25825                      /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
 7f73ee0a4000-7f73ee0a5000 rw-p 00032000 08:01 25825                      /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
 7f73ee0a5000-7f73ee0f2000 r-xp 00000000 08:01 26022                      /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
 7f73ee0f2000-7f73ee2f1000 ---p 0004d000 08:01 26022                      /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
 7f73ee2f1000-7f73ee2f3000 r--p 0004c000 08:01 26022                      /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
 7f73ee2f3000-7f73ee2f4000 rw-p 0004e000 08:01 26022                      /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
 7f73ee2f4000-7f73ee2f6000 rw-p 00000000 00:00 0 
 7f73ee2f6000-7f73ee303000 r-xp 00000000 08:01 26023                      /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
 7f73ee303000-7f73ee503000 ---p 0000d000 08:01 26023                      /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
 7f73ee503000-7f73ee504000 r--p 0000d000 08:01 26023                      /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
 7f73ee504000-7f73ee505000 rw-p 0000e000 08:01 26023                      /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
 7f73ee505000-7f73ee54c000 r-xp 00000000 08:01 25973                      /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
 7f73ee54c000-7f73ee74b000 ---p 00047000 08:01 25973                      /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
 7f73ee74b000-7f73ee74d000 r--p 00046000 08:01 25973                      /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
 7f73ee74d000-7f73ee74f000 rw-p 00048000 08:01 25973                      /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
 7f73ee74f000-7f73ee872000 r-xp 00000000 08:01 25837                      /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
 7f73ee872000-7f73eea71000 ---p 00123000 08:01 25837                      /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
 7f73eea71000-7f73eea7c000 r--p 00122000 08:01 25837                      /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
 7f73eea7c000-7f73eea7e000 rw-p 0012d000 08:01 25837                      /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
 7f73eea7e000-7f73eea7f000 rw-p 00000000 00:00 0 
 7f73eea7f000-7f73eeab3000 r-xp 00000000 08:01 25827                      /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
 7f73eeab3000-7f73eecb2000 ---p 00034000 08:01 25827                      /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
 7f73eecb2000-7f73eecb4000 r--p 00033000 08:01 25827                      /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
 7f73eecb4000-7f73eecb5000 rw-p 00035000 08:01 25827                      /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
 7f73eecb5000-7f73eecd0000 r-xp 00000000 08:01 26027                      /usr/lib/x86_64-linux-gnu/librtmp.so.1
 7f73eecd0000-7f73eeecf000 ---p 0001b000 08:01 26027                      /usr/lib/x86_64-linux-gnu/librtmp.so.1
 7f73eeecf000-7f73eeed0000 r--p 0001a000 08:01 26027                      /usr/lib/x86_64-linux-gnu/librtmp.so.1
 7f73eeed0000-7f73eeed1000 rw-p 0001b000 08:01 26027                      /usr/lib/x86_64-linux-gnu/librtmp.so.1
 7f73eeed1000-7f73eef02000 r-xp 00000000 08:01 27877                      /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
 7f73eef02000-7f73ef102000 ---p 00031000 08:01 27877                      /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
 7f73ef102000-7f73ef103000 r--p 00031000 08:01 27877                      /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
 7f73ef103000-7f73ef104000 rw-p 00032000 08:01 27877                      /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
 7f73ef104000-7f73ef107000 r-xp 00000000 08:01 2052                       /lib/x86_64-linux-gnu/libdl-2.23.so
 7f73ef107000-7f73ef306000 ---p 00003000 08:01 2052                       /lib/x86_64-linux-gnu/libdl-2.23.so
 7f73ef306000-7f73ef307000 r--p 00002000 08:01 2052                       /lib/x86_64-linux-gnu/libdl-2.23.so
 7f73ef307000-7f73ef308000 rw-p 00003000 08:01 2052                       /lib/x86_64-linux-gnu/libdl-2.23.so
 7f73ef308000-7f73ef321000 r-xp 00000000 08:01 2194                       /lib/x86_64-linux-gnu/libz.so.1.2.8
 7f73ef321000-7f73ef520000 ---p 00019000 08:01 2194                       /lib/x86_64-linux-gnu/libz.so.1.2.8
 7f73ef520000-7f73ef521000 r--p 00018000 08:01 2194                       /lib/x86_64-linux-gnu/libz.so.1.2.8
 7f73ef521000-7f73ef522000 rw-p 00019000 08:01 2194                       /lib/x86_64-linux-gnu/libz.so.1.2.8
 7f73ef522000-7f73ef6e2000 r-xp 00000000 08:01 2069                       /lib/x86_64-linux-gnu/libc-2.23.so
 7f73ef6e2000-7f73ef8e2000 ---p 001c0000 08:01 2069                       /lib/x86_64-linux-gnu/libc-2.23.so
 7f73ef8e2000-7f73ef8e6000 r--p 001c0000 08:01 2069                       /lib/x86_64-linux-gnu/libc-2.23.so
 7f73ef8e6000-7f73ef8e8000 rw-p 001c4000 08:01 2069                       /lib/x86_64-linux-gnu/libc-2.23.so
 7f73ef8e8000-7f73ef8ec000 rw-p 00000000 00:00 0 
 7f73ef8ec000-7f73ef902000 r-xp 00000000 08:01 2039                       /lib/x86_64-linux-gnu/libgcc_s.so.1
 7f73ef902000-7f73efb01000 ---p 00016000 08:01 2039                       /lib/x86_64-linux-gnu/libgcc_s.so.1
 7f73efb01000-7f73efb02000 rw-p 00015000 08:01 2039                       /lib/x86_64-linux-gnu/libgcc_s.so.1
 7f73efb02000-7f73efb6b000 r-xp 00000000 08:01 26028                      /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.4.0
 7f73efb6b000-7f73efd6b000 ---p 00069000 08:01 26028                      /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.4.0
 7f73efd6b000-7f73efd6e000 r--p 00069000 08:01 26028                      /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.4.0
 7f73efd6e000-7f73efd6f000 rw-p 0006c000 08:01 26028                      /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.4.0
 7f73efd6f000-7f73efd76000 r-xp 00000000 08:01 2049                       /lib/x86_64-linux-gnu/librt-2.23.so
 7f73efd76000-7f73eff75000 ---p 00007000 08:01 2049                       /lib/x86_64-linux-gnu/librt-2.23.so
 7f73eff75000-7f73eff76000 r--p 00006000 08:01 2049                       /lib/x86_64-linux-gnu/librt-2.23.so
 7f73eff76000-7f73eff77000 rw-p 00007000 08:01 2049                       /lib/x86_64-linux-gnu/librt-2.23.so
 7f73eff77000-7f73f030a000 r-xp 00000000 08:01 30010                      /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20.3.6
 7f73f030a000-7f73f0509000 ---p 00393000 08:01 30010                      /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20.3.6
 7f73f0509000-7f73f050f000 r--p 00392000 08:01 30010                      /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20.3.6
 7f73f050f000-7f73f0582000 rw-p 00398000 08:01 30010                      /usr/lib/x86_64-linux-gnu/libmysqlclient.so.20.3.6
 7f73f0582000-7f73f0587000 rw-p 00000000 00:00 0 
 7f73f0587000-7f73f06f9000 r-xp 00000000 08:01 25851                      /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
 7f73f06f9000-7f73f08f9000 ---p 00172000 08:01 25851                      /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
 7f73f08f9000-7f73f0903000 r--p 00172000 08:01 25851                      /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
 7f73f0903000-7f73f0905000 rw-p 0017c000 08:01 25851                      /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
 7f73f0905000-7f73f0909000 rw-p 00000000 00:00 0 
 7f73f0909000-7f73f0a11000 r-xp 00000000 08:01 2064                       /lib/x86_64-linux-gnu/libm-2.23.so
 7f73f0a11000-7f73f0c10000 ---p 00108000 08:01 2064                       /lib/x86_64-linux-gnu/libm-2.23.so
 7f73f0c10000-7f73f0c11000 r--p 00107000 08:01 2064                       /lib/x86_64-linux-gnu/libm-2.23.so
 7f73f0c11000-7f73f0c12000 rw-p 00108000 08:01 2064                       /lib/x86_64-linux-gnu/libm-2.23.so
 7f73f0c12000-7f73f0c91000 r-xp 00000000 08:01 25877                      /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
 7f73f0c91000-7f73f0e90000 ---p 0007f000 08:01 25877                      /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
 7f73f0e90000-7f73f0e91000 r--p 0007e000 08:01 25877                      /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
 7f73f0e91000-7f73f0e92000 rw-p 0007f000 08:01 25877                      /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
 7f73f0e92000-7f73f0eaa000 r-xp 00000000 08:01 2046                       /lib/x86_64-linux-gnu/libpthread-2.23.so
 7f73f0eaa000-7f73f10a9000 ---p 00018000 08:01 2046                       /lib/x86_64-linux-gnu/libpthread-2.23.so
 7f73f10a9000-7f73f10aa000 r--p 00017000 08:01 2046                       /lib/x86_64-linux-gnu/libpthread-2.23.so
 7f73f10aa000-7f73f10ab000 rw-p 00018000 08:01 2046                       /lib/x86_64-linux-gnu/libpthread-2.23.so
 7f73f10ab000-7f73f10af000 rw-p 00000000 00:00 0 
 7f73f10af000-7f73f10d5000 r-xp 00000000 08:01 2041                       /lib/x86_64-linux-gnu/ld-2.23.so
 7f73f12aa000-7f73f12c1000 rw-p 00000000 00:00 0 
 7f73f12d2000-7f73f12d4000 rw-p 00000000 00:00 0 
 7f73f12d4000-7f73f12d5000 r--p 00025000 08:01 2041                       /lib/x86_64-linux-gnu/ld-2.23.so
 7f73f12d5000-7f73f12d6000 rw-p 00026000 08:01 2041                       /lib/x86_64-linux-gnu/ld-2.23.so
 7f73f12d6000-7f73f12d7000 rw-p 00000000 00:00 0 
 7ffecf859000-7ffecf884000 rw-p 00000000 00:00 0                          [stack]
 7ffecf8cb000-7ffecf8ce000 r--p 00000000 00:00 0                          [vvar]
 7ffecf8ce000-7ffecf8d0000 r-xp 00000000 00:00 0                          [vdso]
 ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
ProcStatus:
 Name:	stratum
 Umask:	0002
 State:	S (sleeping)
 Tgid:	2076
 Ngid:	0
 Pid:	2076
 PPid:	2075
 TracerPid:	0
 Uid:	1000	1000	1000	1000
 Gid:	1000	1000	1000	1000
 FDSize:	64
 Groups:	4 20 24 25 27 29 30 33 44 46 109 110 1000 
 NStgid:	2076
 NSpid:	2076
 NSpgid:	2075
 NSsid:	1662
 VmPeak:	  129816 kB
 VmSize:	  129816 kB
 VmLck:	       0 kB
 VmPin:	       0 kB
 VmHWM:	    8900 kB
 VmRSS:	    8900 kB
 RssAnon:	    1488 kB
 RssFile:	    7412 kB
 RssShmem:	       0 kB
 VmData:	   26324 kB
 VmStk:	     172 kB
 VmExe:	    2332 kB
 VmLib:	   16704 kB
 VmPTE:	     216 kB
 VmPMD:	      12 kB
 VmSwap:	       0 kB
 HugetlbPages:	       0 kB
 Threads:	4
 SigQ:	0/225342
 SigPnd:	0000000000000000
 ShdPnd:	0000000000000000
 SigBlk:	0000000000000000
 SigIgn:	0000000000001000
 SigCgt:	0000000180000000
 CapInh:	0000000000000000
 CapPrm:	0000000000000000
 CapEff:	0000000000000000
 CapBnd:	0000003fffffffff
 CapAmb:	0000000000000000
 NoNewPrivs:	0
 Seccomp:	0
 Cpus_allowed:	ffffffff,ffffffff
 Cpus_allowed_list:	0-63
 Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000003
 Mems_allowed_list:	0-1
 voluntary_ctxt_switches:	31
 nonvoluntary_ctxt_switches:	1
Signal: 11
Uname: Linux 4.11.0-1011-azure x86_64
UserGroups: adm audio cdrom dialout dip floppy lxd netdev plugdev sudo video www-data
_LogindSession: 536`

**Comment by 216k155** [comment]
Because of the coin itself. Please download the test v3.2 and give it a try again.
