### ISSUE TITLE
Error in the install script

### ISSUE THREAD

**Issue by ghosthing** [216k155/Yiimp-PHI1612-Implemented#2]
got this error running the install script

\E[0;33;40mTesting to see if server emails are sent
\E[0m\E[0;33;40m
\E[0minstall.sh: 104: install.sh: Syntax error: word unexpected (expecting ")")

**Comment by crombiecrunch** [comment]
you should grab the install script from my repo, thats official version.

**Comment by ghosthing** [comment]
same error
\E[0minstall.sh: 106: install.sh: Syntax error: word unexpected (expecting ")")
