### ISSUE TITLE
Stratum make failed 

### ISSUE THREAD

**Issue by Ryuspb** [216k155/Yiimp-PHI1612-Implemented#4]
How I can fix it:

make

make[1]: Leaving directory '/var/stratum/sha3'
gcc -g -march=native -DNO_EXCHANGE -DHAVE_CURL mysql_config --cflags --libs -c stratum.cpp
stratum.cpp:163:1: error: invalid conversion from ‘void ()(const char, char*)’ to ‘YAAMP_HASH_FUNCTION {aka void ()(const char, char*, unsigned int)}’ [-fpermissive]
};
^
Makefile:55: recipe for target 'stratum.o' failed
make: *** [stratum.o] Error 1

When try "make" with PHI1612 support Oo

**Comment by vtnplus** [comment]
me too. error when make stratum

**Comment by Ryuspb** [comment]
Thx to discord members for help!
You must change function string - void phi1612_hash(const char* input, char* output, unsigned int len) into both source files!

**Comment by vtnplus** [comment]
nothing todo when chang friend.
maybe you need update phi1612.conf

**Comment by vtnplus** [comment]
yes. work nice :)
now wait open Lux coins :)

**Comment by vtnplus** [comment]
Now Yiim get rewards is 1
Where i can fix it.

**Comment by Ryuspb** [comment]
/var/web/serverconfig.php

define('YAAMP_FEES_MINING', 0);

**Comment by Ryuspb** [comment]
Fixed!
