### ISSUE TITLE
run decred

### ISSUE THREAD

**Issue by ghost** [216k155/Yiimp-PHI1612-Implemented#9]
Hello.
sh run.sh decred
22:06:13: 2017-10-12 starting stratum for decred on server-test.pp.ua:3252
22:06:13: connecting to coind DCR
22:06:13: ERROR: recv1, 0, 0, {"method":"getaccountaddress","params":["default"],"id":"1"},  
22:06:13: ERROR getaccountaddress Decred
22:06:14: DCR getwork retry 1
22:06:14: DCR getwork retry 2
22:06:15: DCR error getwork 

please help.
i install script and run dbcd and dcrwallet

**Comment by itayo** [comment]
well decred is BLAKE256 algorithm.
maybe try your luck on  http://www.github.com/tpruvot/yiimp instead

**Comment by goodthebest** [comment]
@d1mf if you still unable to get it done, you can get in touch with me.

**Comment by ghost** [comment]
Yes. Help please

**Comment by goodthebest** [comment]
what OS are you using?

**Comment by ghost** [comment]
Ubuntu 16.04

**Comment by goodthebest** [comment]
I can get it done, you can contact me here https://github.com/goodthebest

**Comment by ghost** [comment]
i send you email

**Comment by goodthebest** [comment]
I didn't get yet, perhaps you can add the same email in skype to get in touch with me.
